/** Dependencies */
import { primary, secondary, tertiary, error, neutral, neutralVariant } from '../colors';

/**
 * Add the base colors for the plugin
 * @param defaultTheme The default choosen theme when no-class are defined
 * @returns The base items to add
 */
export const addBaseColors = (defaultTheme: 'dark' | 'light' = 'dark') => {
  /** Default dark theme colors */
  const darkThemeColors = {
    '--color-primary': primary['80'].array().join(' '),
    '--color-on-primary': primary['20'].array().join(' '),
    '--color-secondary': secondary['80'].array().join(' '),
    '--color-on-secondary': secondary['20'].array().join(' '),
    '--color-tertiary': tertiary['80'].array().join(' '),
    '--color-on-tertiary': tertiary['20'].array().join(' '),
    '--color-error': error['80'].array().join(' '),
    '--color-on-error': error['20'].array().join(' '),
    '--color-primary-container': primary['30'].array().join(' '),
    '--color-on-primary-container': primary['90'].array().join(' '),
    '--color-secondary-container': secondary['30'].array().join(' '),
    '--color-on-secondary-container': secondary['90'].array().join(' '),
    '--color-tertiary-container': tertiary['30'].array().join(' '),
    '--color-on-tertiary-container': tertiary['90'].array().join(' '),
    '--color-error-container': error['30'].array().join(' '),
    '--color-on-error-container': error['90'].array().join(' '),
    '--color-primary-fixed': primary['90'].array().join(' '),
    '--color-primary-fixed-dim': primary['80'].array().join(' '),
    '--color-on-primary-fixed': primary['10'].array().join(' '),
    '--color-on-primary-fixed-variant': primary['30'].array().join(' '),
    '--color-secondary-fixed': secondary['90'].array().join(' '),
    '--color-secondary-fixed-dim': secondary['80'].array().join(' '),
    '--color-on-secondary-fixed': secondary['10'].array().join(' '),
    '--color-on-secondary-fixed-variant': secondary['30'].array().join(' '),
    '--color-tertiary-fixed': tertiary['90'].array().join(' '),
    '--color-tertiary-fixed-dim': tertiary['80'].array().join(' '),
    '--color-on-tertiary-fixed': tertiary['10'].array().join(' '),
    '--color-on-tertiary-fixed-variant': tertiary['30'].array().join(' '),
    '--color-surface': neutral['6'].array().join(' '),
    '--color-surface-dim': neutral['6'].array().join(' '),
    '--color-surface-bright': neutral['24'].array().join(' '),
    '--color-surface-variant': neutralVariant['30'].array().join(' '),
    '--color-surface-container-lowest': neutral['4'].array().join(' '),
    '--color-surface-container-low': neutral['10'].array().join(' '),
    '--color-surface-container': neutral['12'].array().join(' '),
    '--color-surface-container-high': neutral['17'].array().join(' '),
    '--color-surface-container-highest': neutral['22'].array().join(' '),
    '--color-on-surface': neutral['90'].array().join(' '),
    '--color-on-surface-variant': neutralVariant['80'].array().join(' '),
    '--color-outline': neutralVariant['60'].array().join(' '),
    '--color-outline-variant': neutralVariant['30'].array().join(' '),
    '--color-inverse-surface': neutral['90'].array().join(' '),
    '--color-inverse-on-surface': neutral['20'].array().join(' '),
    '--color-inverse-primary': primary['40'].array().join(' '),
    '--color-scrim': neutral['0'].array().join(' '),
    '--color-shadow': neutral['0'].array().join(' ')
  };

  /** Default light theme colors */
  const lightThemeColor = {
    '--color-primary': primary['40'].array().join(' '),
    '--color-on-primary': primary['100'].array().join(' '),
    '--color-secondary': secondary['40'].array().join(' '),
    '--color-on-secondary': secondary['100'].array().join(' '),
    '--color-tertiary': tertiary['40'].array().join(' '),
    '--color-on-tertiary': tertiary['100'].array().join(' '),
    '--color-error': error['40'].array().join(' '),
    '--color-on-error': error['100'].array().join(' '),
    '--color-primary-container': primary['90'].array().join(' '),
    '--color-on-primary-container': primary['10'].array().join(' '),
    '--color-secondary-container': secondary['90'].array().join(' '),
    '--color-on-secondary-container': secondary['10'].array().join(' '),
    '--color-tertiary-container': tertiary['90'].array().join(' '),
    '--color-on-tertiary-container': tertiary['10'].array().join(' '),
    '--color-error-container': error['90'].array().join(' '),
    '--color-on-error-container': error['10'].array().join(' '),
    '--color-primary-fixed': primary['90'].array().join(' '),
    '--color-primary-fixed-dim': primary['80'].array().join(' '),
    '--color-on-primary-fixed': primary['10'].array().join(' '),
    '--color-on-primary-fixed-variant': primary['30'].array().join(' '),
    '--color-secondary-fixed': secondary['90'].array().join(' '),
    '--color-secondary-fixed-dim': secondary['80'].array().join(' '),
    '--color-on-secondary-fixed': secondary['10'].array().join(' '),
    '--color-on-secondary-fixed-variant': secondary['30'].array().join(' '),
    '--color-tertiary-fixed': tertiary['90'].array().join(' '),
    '--color-tertiary-fixed-dim': tertiary['80'].array().join(' '),
    '--color-on-tertiary-fixed': tertiary['10'].array().join(' '),
    '--color-on-tertiary-fixed-variant': tertiary['30'].array().join(' '),
    '--color-surface': neutral['99'].array().join(' '),
    '--color-surface-dim': neutral['87'].array().join(' '),
    '--color-surface-bright': neutral['99'].array().join(' '),
    '--color-surface-variant': neutralVariant['90'].array().join(' '),
    '--color-surface-container-lowest': neutral['100'].array().join(' '),
    '--color-surface-container-low': neutral['96'].array().join(' '),
    '--color-surface-container': neutral['94'].array().join(' '),
    '--color-surface-container-high': neutral['92'].array().join(' '),
    '--color-surface-container-highest': neutral['90'].array().join(' '),
    '--color-on-surface': neutral['10'].array().join(' '),
    '--color-on-surface-variant': neutralVariant['30'].array().join(' '),
    '--color-outline': neutralVariant['50'].array().join(' '),
    '--color-outline-variant': neutralVariant['80'].array().join(' '),
    '--color-inverse-surface': neutral['20'].array().join(' '),
    '--color-inverse-on-surface': neutral['95'].array().join(' '),
    '--color-inverse-primary': primary['80'].array().join(' '),
    '--color-scrim': neutral['0'].array().join(' '),
    '--color-shadow': neutral['0'].array().join(' ')
  };

  /** Create the elements base for root, dark and light theme */
  return {
    ':root': defaultTheme === 'dark' ? darkThemeColors : lightThemeColor,
    '.dark': darkThemeColors,
    '.light': lightThemeColor
  };
};

/** Constant for the extend color of the plugin */
export const extendColors = {
  'primary': 'rgba(var(--color-primary))',
  'on-primary': 'rgba(var(--color-on-primary))',
  'secondary': 'rgba(var(--color-secondary))',
  'on-secondary': 'rgba(var(--color-on-secondary))',
  'tertiary': 'rgba(var(--color-tertiary))',
  'on-tertiary': 'rgba(var(--color-on-tertiary))',
  'error': 'rgba(var(--color-error))',
  'on-error': 'rgba(var(--color-on-error))',
  'primary-container': 'rgba(var(--color-primary-container))',
  'on-primary-container': 'rgba(var(--color-on-primary-container))',
  'secondary-container': 'rgba(var(--color-secondary-container))',
  'on-secondary-container': 'rgba(var(--color-on-secondary-container))',
  'tertiary-container': 'rgba(var(--color-tertiary-container))',
  'on-tertiary-container': 'rgba(var(--color-on-tertiary-container))',
  'error-container': 'rgba(var(--color-error-container))',
  'on-error-container': 'rgba(var(--color-on-error-container))',
  'primary-fixed': 'rgba(var(--color-primary-fixed))',
  'primary-fixed-dim': 'rgba(var(--color-primary-fixed-dim))',
  'on-primary-fixed': 'rgba(var(--color-on-primary-fixed))',
  'on-primary-fixed-variant': 'rgba(var(--color-on-primary-fixed-variant))',
  'secondary-fixed': 'rgba(var(--color-secondary-fixed))',
  'secondary-fixed-dim': 'rgba(var(--color-secondary-fixed-dim))',
  'on-secondary-fixed': 'rgba(var(--color-on-secondary-fixed))',
  'on-secondary-fixed-variant': 'rgba(var(--color-on-secondary-fixed-variant))',
  'tertiary-fixed': 'rgba(var(--color-tertiary-fixed))',
  'tertiary-fixed-dim': 'rgba(var(--color-tertiary-fixed-dim))',
  'on-tertiary-fixed': 'rgba(var(--color-on-tertiary-fixed))',
  'on-tertiary-fixed-variant': 'rgba(var(--color-on-tertiary-fixed-variant))',
  'surface': 'rgba(var(--color-surface))',
  'surface-dim': 'rgba(var(--color-surface-dim))',
  'surface-bright': 'rgba(var(--color-surface-bright))',
  'surface-variant': 'rgba(var(--color-surface-variant))',
  'surface-container-lowest': 'rgba(var(--color-surface-container-lowest))',
  'surface-container-low': 'rgba(var(--color-surface-container-low))',
  'surface-container': 'rgba(var(--color-surface-container))',
  'surface-container-high': 'rgba(var(--color-surface-container-high))',
  'surface-container-highest': 'rgba(var(--color-surface-container-highest))',
  'on-surface': 'rgba(var(--color-on-surface))',
  'on-surface-variant': 'rgba(var(--color-on-surface-variant))',
  'outline': 'rgba(var(--color-outline))',
  'outline-variant': 'rgba(var(--color-outline-variant))',
  'inverse-surface': 'rgba(var(--color-inverse-surface))',
  'inverse-on-surface': 'rgba(var(--color-inverse-on-surface))',
  'inverse-primary': 'rgba(var(--color-inverse-primary))',
  'scrim': 'rgba(var(--color-scrim))',
  'shadow': 'rgba(var(--color-shadow))',
  'background': 'rgba(var(--color-surface))',
  'on-background': 'rgba(var(--color-on-surface))'
};
